global using System;
global using System.Diagnostics;
global using System.IO;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Input;
global using System.Windows.Media;
global using System.Windows.Media.Animation;
global using System.Windows.Threading;
global using System.Linq;
global using VideoSorter.Views;
global using System.Collections.Generic;
global using static System.Diagnostics.Trace;
global using static System.Media.SystemSounds;
